name: TorchScript Models

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  build-torchscript:
    name: Build TorchScript models
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install .
      - name: Export models to TorchScript
        run: |
          seisbench-phasenet-export dist/torchscript-seisbench-phasenet/
          cd dist/torchscript-seisbench-phasenet/
          tar -zcvf ../torchscript-seisbench-phasenet.tar.gz *.pt
      - name: Upload TorchScript PhaseNet artifacts
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: torchscript-seisbench-phasenet
          path: dist/torchscript-seisbench-phasenet/*.pt
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/torchscript-seisbench-phasenet.tar.gz
